---
- name: Converge
  hosts: all
  vars:
    github_api_token: "{{ lookup('ansible.builtin.env','GAK_GITHUB_API_TOKEN') }}"
    github_organization: "{{ lookup('ansible.builtin.env','GAK_GITHUB_ORGANIZATION') }}"
    github_admin_team_name: "{{ lookup('ansible.builtin.env','GAK_GITHUB_ADMIN_TEAM_NAME') }}"
    github_user_team_name: "{{ lookup('ansible.builtin.env','GAK_GITHUB_USER_TEAM_NAME') }}"
  roles:
    - terjekv.github_authorized_keys
