---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint `git ls-files '*.yaml' '*.yml'`
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: "centos:centos7"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/tmp/docker.sock
    privileged: true
    pre_build_image: false

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /var/tmp
      ansible_user: centos
      ansible_docker_user: centos
  env:
    ANSIBLE_VERBOSITY: 3
verifier:
  name: testinfra
