---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Create docker.sock
      raw: touch /var/run/docker.sock
      become: true
      changed_when: false

    - name: Move docker.sock from tmp
      raw: mount --move /tmp/docker.sock /var/run/docker.sock
      become: true
      changed_when: false

    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (on Redhat).
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Ensure policycoreutils is available if required.
      package:
        name: policycoreutils
        state: present
      when: ansible_os_family == 'RedHat'
